name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsfml-dev cmake build-essential
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -DENABLE_TESTS=ON
    
    - name: Build
      run: |
        cd build
        make -j$(nproc)
    
    - name: Run tests
      run: |
        cd build
        ./UnitTests
    
    - name: Build game
      run: |
        cd build
        make SigmaHackNSlash
    
    - name: Upload game binary
      uses: actions/upload-artifact@v3
      with:
        name: game-binary
        path: build/SigmaHackNSlash 